config/routes.rb
QaTest::Application.routes.draw do

  resources :authentications

  resources :tags
  post "comments/save"
  match 'auth/:provider/callback' => 'authentications#create'
  post "answers/rank"
  post "answers/save"
  post 'quests/like'

  devise_for :users, :controllers => {:registrations => 'registrations'}

  resources :quests
  root :to => 'quests#index'
  
namespace :api do
  resources :questions
end

end

app/models/quest.rb
class Quest < ActiveRecord::Base
  belongs_to :user
  has_many :answers
  has_many :comments
  attr_accessible :answers_c, :body, :comments_c, :likes, :tags, :theme, :user_id, :review_c
  
  validates :body, :presence => true
  validates :theme, :presence => true
  validates :tags, :presence => true
end

app/controllers/quests_controller.rb
class QuestsController < ApplicationController
  # GET /quests
  # GET /quests.json
  def index
    @quests = Quest.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @quests }
    end
  end

  # GET /quests/1
  # GET /quests/1.json
  def show
    @quest = Quest.find(params[:id])
    @quest.review+=1
    @quest.save
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @quest }
    end
  end

  # GET /quests/new
  # GET /quests/new.json
  def new
    @quest = Quest.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @quest }
    end
  end

  # GET /quests/1/edit
  def edit
    @quest = Quest.find(params[:id])
  end

  # POST /quests
  # POST /quests.json
  def create
    @quest = Quest.new(params[:quest]) #create new question 
    @quest.likes=0 # set likes count
    @quest.review=0 # set reviews count
    if current_user  # if session has been started
      @quest.user_id=current_user.id
    else # as anonymous
      @quest.user_id=1
    end      
    respond_to do |format|
      if @quest.save
        format.html { redirect_to @quest, notice: 'Quest was successfully created.' }
        format.json { render json: @quest, status: :created, location: @quest }
      else
        format.html { render action: "new" }
        format.json { render json: @quest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /quests/1
  # PUT /quests/1.json
  def update
    @quest = Quest.find(params[:id])

    respond_to do |format|
      if @quest.update_attributes(params[:quest])
        format.html { redirect_to @quest, notice: 'Quest was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @quest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quests/1
  # DELETE /quests/1.json
  def destroy
    @quest = Quest.find(params[:id])
    @quest.destroy

    respond_to do |format|
      format.html { redirect_to quests_url }
      format.json { head :no_content }
    end
  end

  def like
       @quest_params = {  # get params from Ajax
        :id => params[:q_id]  
       }
        @quest= Quest.find(params[:q_id] ) # find a question
      @quest.likes+=1 # increment likes
      @quest.save() # update questions params in db
      @response = {:status => "true",
                           :data => @quest.likes }
    render json: @response    
  end    
end

app/helpers/quests_helper.rb
module QuestsHelper
end

app/views/quests/_form.html.erb
<div align='center'>
<%= form_for(@quest) do |f| %>
  <% if @quest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@quest.errors.count, "error") %> prohibited this quest from being saved:</h2>

      <ul>
      <% @quest.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class='content'>
  <div class="field">
    <%= f.label :Topic %><br />
    <%= f.text_field :theme  %>
  </div>
  <div class="field_q">
    <%= f.label :Question %><br />
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :tags %><br />
    <%= f.text_field :tags %>
  </div>
 
  <div class="actions">
    <%= f.submit %>
  </div>
 </div> 
<% end %>
</div>

app/views/quests/edit.html.erb
<h1>Editing quest</h1>

<%= render 'form' %>

<%= link_to 'Show', @quest %> |
<%= link_to 'Back', quests_path %>

app/views/quests/index.html.erb
<a name="up"></a>
<h2>Q&A</h2>
<div class='right'>
  <div class="new">
    <%= link_to 'New Question', new_quest_path %>
    <% if (current_user)&&(current_user.id<5) %>
     | <%= link_to 'New Tag', new_tag_path %>
    <%end%>
  </div>
  <br>
  <div class='cloud'>
    <% Tag.all.each do |tag| %>    
      <% if tag.rank == 1 %>
      <span class='top'>
        <%= link_to tag.body, tag %></td>
      </span>
      <% else %>
      <span class='tag'>
      <%= link_to tag.body, tag %></td>
      </span>
      <% end %>
  <% end %>
  </div>
</div>

<div class='content'>
<% @quests.sort_by(&:created_at).reverse.each do |quest| %>
<table>
   <tr>
    <td><%= gravatar_image_tag User.find(quest.user_id).email %></td>
    <td class='topic'><%= link_to quest.theme, quest    %>
      <p class='date'>
        <% if quest.created_at.to_date==Time.now.to_date %>
          <%= quest.created_at.strftime("%H:%M:%S") %>
        <%else%>
          <%= quest.created_at.to_date %>
        <%end%>  
      </p>
    </td>
   </tr>
   <tr>
    <td>
        <%if User.find(quest.user_id).nickname then%>
          <b><%= User.find(quest.user_id).nickname%></b>
        <%else%>
          <b><%= User.find(quest.user_id).email %></b>
        <%end%>
    </td>
    <td>
      <span>Reviews:</span>
      <%= quest.review %>
      <span> |</span>
      <span>Answers:</span>
      <%=  quest.answers.count%>
      <span> |</span>
      <span>Comments:</span>
      <%= quest.comments.count %>
      <span> |</span>
      <span>Likes:</span>
      <%= quest.likes %>
      
      <%if (current_user)&&(quest.user_id==current_user.id) then %>
        <span> |</span>
        <%= link_to 'Edit', edit_quest_path(quest) %>
        <span> |</span>
        <%= link_to 'Destroy', quest, method: :delete, data: { confirm: 'Are you sure?' } %>
      <%end%>
    </td>
   </tr>    
   <tr>
   <td></td>
   <td><b>Tags: <%= quest.tags %></b></td>
   </tr>
   
   </table>
<hr>   
<% end %>

</div>

<br />


<span class='up'>
<a href='#up'>Up</a>
</span>

app/views/quests/new.html.erb
<h2>New question</h2>

<%= render 'form' %>

<span class='back'>
<%= link_to 'Back', quests_path %>
</span>

app/views/quests/show.html.erb
<p id="notice"><%= notice %></p>
<a name="up"></a>

<h2>  
   <span id='q_id' class='<%= @quest.id %>'><%= @quest.theme %></span>  
</h2>



<table class='content'>
  <tr>
    <td>
      <%= gravatar_image_tag User.find(@quest.user_id).email %>
    </td>
    <td>
      <b>
        <%= @quest.body %>
      </b>
    </td>
  </tr>
  <tr>
    <td> <b>
      <% if User.find(@quest.user_id).nickname!=nil %>
        <%= User.find(@quest.user_id).nickname %>
      <% else %>
        <%= User.find(@quest.user_id).email %>
      <% end %>  </b>
    </td>
    <td>
       <p> <span>Likes: </span>
          <span id='like_c'><%= @quest.likes %></span>
        <% if current_user %>
          <input id='like' type="button" value='+1'  />
        <% else %>
          <h2>Only authorized users can like the questions </h2>
        <% end %></p>
    </td>
  </tr>
</table>

<div class='content'>

<% @quest.answers.sort_by(&:rank).reverse.each do |answer| %>
<hr>
<table  class= 'ava'>
  <tr>
    <td><%= gravatar_image_tag User.find(answer.user_id).email %></td>
    <td><%= answer.data %></td>
  </tr>
  <tr> 
    <td>
      <% if User.find(answer.user_id).nickname!=nil %>
        <%= User.find(answer.user_id).nickname %>
        <% else %>
        <%= User.find(answer.user_id).email %>
      <% end %></td>
    <td>Rank <span class='rank <%= answer.id %> '><%= answer.rank %> 
    <% if current_user %>
    <span class= 'inc <%= answer.id %> '>+</span> 
    <span>|</span> 
    <span class= 'dec <%= answer.id %> '>-</span></span> 
    <span class='com' id= '<%= answer.id %> '>New comment</span></td>
    <%end%>
  </tr>  
</table>
<hr>
        <% answer.comments.each do |comment| %>
        <div class='comments'>
         <h2><% if User.find(comment.user_id).nickname %>
                          <%= User.find(comment.user_id).nickname %>
                      <% else %>
                          <%= User.find(comment.user_id).email %>
                      <% end %>  </h2>
          <p><%= gravatar_image_tag User.find(comment.user_id).email %>
              <%= comment.body %>
          </p>
           
        </div>
        
        <div class='clearfix'></div>
        <%end%>
<% end %>

<% if current_user %>
<hr>
<h2>Your answer</h2>
<textarea id='answer' rows="10" cols="95" aligin= center >
</textarea>
<input id='answ' type="button" value='Send answer'  />



<% else %>
<h2>Only authorized users can answer and comment the questions </h2>
<% end %>

</div>

<div align="center" class='comment'>
  <div class='com_head'><h2>New comment <span id='close'>close</span></h2> </div>
  <%if current_user%>
    <%= gravatar_image_tag current_user.email %>
  <%end%> 
  <br>
  <span><% if (current_user)&&(current_user.nickname) %>
        <%= current_user.nickname %>
        <% elsif current_user %>
        <%= current_user.email %>
      <% end %></span>
      <div class='clearfix'></div>
      <br>
  <textarea id='comt' rows="5" cols="75" aligin= center autofocus >
  </textarea>
  <input id='add_com' type="button" value='OK', size= 30px/> 
  <br>
  <br>
</div>

<span class='back'>
<%= link_to 'Back', quests_path %>
</span>

<span class='up'>
<a href='#up'>Up</a>
</span>