config/routes.rb
QaTest::Application.routes.draw do

  resources :authentications

  resources :tags
  post "comments/save"
  match 'auth/:provider/callback' => 'authentications#create'
  post "answers/rank"
  post "answers/save"
  post 'quests/like'

  devise_for :users, :controllers => {:registrations => 'registrations'}

  resources :quests
  root :to => 'quests#index'
  
namespace :api do
  resources :questions
end

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :body, :rank
  validates :body, :presence => true
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tags }
    end
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
    @tag = Tag.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tag }
    end
  end

  # GET /tags/new
  # GET /tags/new.json
  def new
    @tag = Tag.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tag }
    end
  end

  # GET /tags/1/edit
  def edit
    @tag = Tag.find(params[:id])
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(params[:tag])

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render json: @tag, status: :created, location: @tag }
      else
        format.html { render action: "new" }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tags/1
  # PUT /tags/1.json
  def update
    @tag = Tag.find(params[:id])

    respond_to do |format|
      if @tag.update_attributes(params[:tag])
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy

    respond_to do |format|
      format.html { redirect_to tags_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.erb
<%= form_for(@tag) do |f| %>
  <% if @tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% @tag.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_field :body %>
  </div>
  <div class="field">
    <%= f.label :rank %><br />
    <%= f.number_field :rank %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<h1>Editing tag</h1>

<%= render 'form' %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<h2>Listing tags</h2>
<div class='content'>
<table>
  

<% @tags.each do |tag| %>
  <tr>
    
    <td><%= link_to tag.body, tag %></td>
   <% if (current_user)&&(current_user.id<5) %>
    <td><%= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <%end%>
  </tr>
<% end %>
</table>

<br />
<% if (current_user)&&(current_user.id<5) %>
<%= link_to 'New Tag', new_tag_path %>
<%end%>
</div>
<span class='back'>
<%= link_to 'Main', quests_path %>
</span>

app/views/tags/new.html.erb
<h2>New tag</h2>
<div class='content'>
<%= render 'form' %>
</div>
<%= link_to 'Back', tags_path %>

app/views/tags/show.html.erb
<p id="notice"><%= notice %></p>

<h2><%= @tag.body %></h2>
<div class='content'>
<% Quest.all.each do |quest| %>
<% if quest.tags.downcase.include? @tag.body.downcase %>
<table>
   <tr>
    <td><%= gravatar_image_tag User.find(quest.user_id).email %></td>
    <td class='topic'><%= link_to quest.theme, quest    %>
      <p class='date'>
        <% if quest.created_at.to_date==Time.now.to_date %>
          <%= quest.created_at.strftime("%H:%M:%S") %>
        <%else%>
          <%= quest.created_at.to_date %>
        <%end%>  
      </p>
    </td>
   </tr>
   <tr>
    <td>
        <%if User.find(quest.user_id).nickname then%>
          <b><%= User.find(quest.user_id).nickname%></b>
        <%else%>
          <b><%= User.find(quest.user_id).email %></b>
        <%end%>
    </td>
    <td>
      <span>Reviews:</span>
      <%= quest.review %>
      <span> |</span>
      <span>Answers:</span>
      <%=  quest.answers.count%>
      <span> |</span>
      <span>Comments:</span>
      <%= quest.comments.count %>
      <span> |</span>
      <span>Likes:</span>
      <%= quest.likes %>
      
      <%if (current_user)&&(quest.user_id==current_user.id) then %>
        <span> |</span>
        <%= link_to 'Edit', edit_quest_path(quest) %>
        <span> |</span>
        <%= link_to 'Destroy', quest, method: :delete, data: { confirm: 'Are you sure?' } %>
      <%end%>
    </td>
   </tr>    
   
   </table>
<hr>   
<% end %>
<% end %>

</div>

<span class='back'>
<%= link_to 'Main', quests_path %>
</span>